from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime, Text
from sqlalchemy.orm import relationship
from database import Base
import datetime


class User(Base):
    __tablename__ = "users"

    id         = Column(Integer, primary_key=True, index=True)
    name       = Column(String(100), nullable=False)
    age        = Column(Integer)
    email      = Column(String(250), unique=True, nullable=False, index=True)
    password   = Column(String(250), nullable=False)   # always stores bcrypt hash
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships — cascade delete keeps DB clean when a user is removed
    progress      = relationship("UserProgress",      back_populates="owner", cascade="all, delete")
    quiz_results  = relationship("QuizResult",        back_populates="owner", cascade="all, delete")
    doubt_history = relationship("DoubtHistory",      back_populates="owner", cascade="all, delete")
    sim_history   = relationship("SimulationHistory", back_populates="owner", cascade="all, delete")
    notes_history = relationship("NotesHistory",      back_populates="owner", cascade="all, delete")


class UserProgress(Base):
    """Aggregated per-topic performance. Upserted after every quiz."""
    __tablename__ = "user_progress"

    id               = Column(Integer, primary_key=True, index=True)
    user_id          = Column(Integer, ForeignKey("users.id"))
    topic_name       = Column(String(100), index=True)
    score            = Column(Float,   default=0.0)   # latest quiz score (%)
    accuracy         = Column(Float,   default=0.0)   # rolling average accuracy (%)
    hints_used       = Column(Integer, default=0)
    questions_solved = Column(Integer, default=0)
    time_taken       = Column(Integer, default=0)     # cumulative seconds
    time_stamp       = Column(DateTime, default=datetime.datetime.utcnow)

    owner = relationship("User", back_populates="progress")


class QuizResult(Base):
    """One row per quiz attempt — used for analytics and weakness detection."""
    __tablename__ = "quiz_results"

    id              = Column(Integer, primary_key=True, index=True)
    user_id         = Column(Integer, ForeignKey("users.id"))
    topic           = Column(String(100), nullable=False)
    score           = Column(Float)               # percentage
    total_questions = Column(Integer)
    correct_answers = Column(Integer)
    time_taken      = Column(Integer)             # seconds
    created_at      = Column(DateTime, default=datetime.datetime.utcnow)

    owner = relationship("User", back_populates="quiz_results")


class DoubtHistory(Base):
    """Stores every question the student asked the AI tutor."""
    __tablename__ = "doubt_history"

    id         = Column(Integer, primary_key=True, index=True)
    user_id    = Column(Integer, ForeignKey("users.id"))
    question   = Column(Text, nullable=False)
    answer     = Column(Text)
    topic      = Column(String(100), default="General")
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    owner = relationship("User", back_populates="doubt_history")


class SimulationHistory(Base):
    """Records every simulation generated by a student."""
    __tablename__ = "simulation_history"

    id         = Column(Integer, primary_key=True, index=True)
    user_id    = Column(Integer, ForeignKey("users.id"))
    concept    = Column(String(200), nullable=False)
    gif_url    = Column(String(500))
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    owner = relationship("User", back_populates="sim_history")


class NotesHistory(Base):
    """Stores AI-generated revision notes per topic."""
    __tablename__ = "notes_history"

    id         = Column(Integer, primary_key=True, index=True)
    user_id    = Column(Integer, ForeignKey("users.id"))
    topic      = Column(String(100), nullable=False)
    notes      = Column(Text)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    owner = relationship("User", back_populates="notes_history")
